### ISSUE TITLE
Missing support for defineMessage

### ISSUE THREAD

**Issue by henrymunro** [godaddy/eslint-plugin-react-intl#7]
React-intl supports both `defineMessages` and `defineMessage` functions ([docs](https://formatjs.io/docs/react-intl/api/#definemessagesdefinemessage)).

This plugin only has support for `defineMessages` ([defined here](https://github.com/godaddy/eslint-plugin-react-intl/blob/master/lib/util/findNodes.js#L43:L55)).

I can take a look and raise a PR.

**Comment by kinetifex** [comment]
Thanks for reporting! We'll take look.

**Comment by kinetifex** [comment]
Fixed in `@godaddy/eslint-plugin-react-intl@1.1.0`
